// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-customer-service");

export default function Pageiptv_customer_service() {
  return <SeoPage slug="iptv-customer-service" />;
}
