// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-nvidia-shield");

export default function Pageiptv_nvidia_shield() {
  return <SeoPage slug="iptv-nvidia-shield" />;
}
