// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-vs-bell");

export default function Pageiptv_vs_bell() {
  return <SeoPage slug="iptv-vs-bell" />;
}
