// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-ps5");

export default function Pageiptv_ps5() {
  return <SeoPage slug="iptv-ps5" />;
}
