// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-new-brunswick");

export default function Pageiptv_new_brunswick() {
  return <SeoPage slug="iptv-new-brunswick" />;
}
