// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-victoria");

export default function Pageiptv_victoria() {
  return <SeoPage slug="iptv-victoria" />;
}
