// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-stanley-cup-playoffs");

export default function Pageiptv_stanley_cup_playoffs() {
  return <SeoPage slug="iptv-stanley-cup-playoffs" />;
}
