// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("siptv-app");

export default function Pagesiptv_app() {
  return <SeoPage slug="siptv-app" />;
}
