// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-kitchener-waterloo");

export default function Pageiptv_kitchener_waterloo() {
  return <SeoPage slug="iptv-kitchener-waterloo" />;
}
