// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-st-catharines");

export default function Pageiptv_st_catharines() {
  return <SeoPage slug="iptv-st-catharines" />;
}
