// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("formuler-z10-z8");

export default function Pageformuler_z10_z8() {
  return <SeoPage slug="formuler-z10-z8" />;
}
