// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-provider-alternatives");

export default function Pageiptv_provider_alternatives() {
  return <SeoPage slug="iptv-provider-alternatives" />;
}
