// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-kelowna");

export default function Pageiptv_kelowna() {
  return <SeoPage slug="iptv-kelowna" />;
}
