// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("tivimate-premium");

export default function Pagetivimate_premium() {
  return <SeoPage slug="tivimate-premium" />;
}
