// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("ott-navigator");

export default function Pageott_navigator() {
  return <SeoPage slug="ott-navigator" />;
}
