// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-surrey");

export default function Pageiptv_surrey() {
  return <SeoPage slug="iptv-surrey" />;
}
