// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-generic-android-box");

export default function Pageiptv_generic_android_box() {
  return <SeoPage slug="iptv-generic-android-box" />;
}
