// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-xbox");

export default function Pageiptv_xbox() {
  return <SeoPage slug="iptv-xbox" />;
}
