// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-smarters-samsung-tv");

export default function Pageiptv_smarters_samsung_tv() {
  return <SeoPage slug="iptv-smarters-samsung-tv" />;
}
