// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("mag-524-iptv");

export default function Pagemag_524_iptv() {
  return <SeoPage slug="mag-524-iptv" />;
}
