// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-web-browser");

export default function Pageiptv_web_browser() {
  return <SeoPage slug="iptv-web-browser" />;
}
