// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("dreamlink-iptv");

export default function Pagedreamlink_iptv() {
  return <SeoPage slug="dreamlink-iptv" />;
}
