// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-corner-brook");

export default function Pageiptv_corner_brook() {
  return <SeoPage slug="iptv-corner-brook" />;
}
