// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("what-is-iptv");

export default function Pagewhat_is_iptv() {
  return <SeoPage slug="what-is-iptv" />;
}
