// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-global-tv");

export default function Pageiptv_global_tv() {
  return <SeoPage slug="iptv-global-tv" />;
}
