// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-thunder-bay");

export default function Pageiptv_thunder_bay() {
  return <SeoPage slug="iptv-thunder-bay" />;
}
