// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-winter-buffering");

export default function Pageiptv_winter_buffering() {
  return <SeoPage slug="iptv-winter-buffering" />;
}
