// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-trois-rivieres");

export default function Pageiptv_trois_rivieres() {
  return <SeoPage slug="iptv-trois-rivieres" />;
}
