// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-space-speed-brand-names");

export default function Pageiptv_space_speed_brand_names() {
  return <SeoPage slug="iptv-space-speed-brand-names" />;
}
