// Groups for provider-name searches (first match wins). Shared by seo/build-keyword-map.mjs and brand-groups.mjs.
export const BRAND_GROUPS = [
  { slug: "iptv-animal-brand-names", re: /eagle|lion|shark|wolf|tiger|dragon|bird|pelican|gecko|spider|falcon|cobra|viper|fox|panda|dodo|beast|monster|hulk|trex|dino/i,
    label: "animal-themed", sample: ["Eagle IPTV", "Lion IPTV", "Shark IPTV"], title: "Eagle, Lion, Shark & Wolf IPTV Names — Compare | MapleHD",
    intro: "Animal names such as eagle, lion, shark, wolf, tiger and dragon are among the most common IPTV brand words.", pattern: "Animal names are easy to remember and to brand with a logo, so many unrelated services adopt them. Two \"Eagle\" or \"Lion\" services may have nothing in common, so never assume that a review of one applies to another." },
  { slug: "iptv-royal-premium-brand-names", re: /royal|king|dynasty|empire|legends|glory|fortune|deluxe|ultimate|universal|universe|infinity|eternal|premier|prime|crystal|sapphire|opus|maestro|magnum|supernova|super|great|good|awesome|perfect|pure|real|strong|epic|elite/i,
    label: "royal and premium-sounding", sample: ["Royal IPTV", "Ultimate IPTV", "Crystal IPTV"], title: "Royal, Ultimate, Crystal & Premium IPTV Names | MapleHD",
    intro: "Names that promise quality (royal, ultimate, crystal, empire, perfect, great) are common because they sound trustworthy, but a name is not a guarantee.", pattern: "Quality words are marketing, not evidence. A service calling itself perfect, great or ultimate has told you its aspiration rather than its track record, so ask for a trial and read the terms instead." },
  { slug: "iptv-space-speed-brand-names", re: /nasa|nova|star|space|galaxy|delta|gamma|hydrogen|hypersonic|matrix|nitro|thunder|rapid|fast|flux|electro|neo|astra|blitzen|5g|helix|evo|sonic|zoom|quzu|jarvis|unifi|ironiptv|mxl|smartgo|smartone|igate|itec|iview|harmo|neox/i,
    label: "space, speed and tech-themed", sample: ["Nova IPTV", "Star IPTV", "Rapid IPTV"], title: "Nova, Star, Rapid & Fast IPTV Names — Compare | MapleHD",
    intro: "Space and speed words such as nova, star, rapid, nitro and 5G are popular in IPTV branding to suggest performance.", pattern: "Speed words imply fast channel changes and no buffering, but streaming speed depends on your own internet connection and the provider's server capacity. Test on a busy evening rather than trusting a name that says fast." },
  { slug: "iptv-character-brand-names", re: /ninja|ghost|venom|sniper|voodoo|wizard|necro|joker|mario|marvel|bob\b|mom|elon|zina|yeah|lazy|lex|guru|bravo|ace\b|blink|blended|crazy|dark|domino|hot|sleek|purple|redline|blue tv|magic|phoenix|avatar|aroma|area51|nikon|moul|datoo/i,
    label: "character and attitude-themed", sample: ["Ninja IPTV", "Ghost IPTV", "Magic IPTV"], title: "Ninja, Ghost, Magic & Purple IPTV Names | MapleHD",
    intro: "Playful and character names (ninja, ghost, magic, joker, purple) are used by many IPTV brands, often with no connection between them.", pattern: "Character and pop-culture names sometimes borrow from films, games or celebrities without any link to them. Treat the name as decoration and judge the service on what you can verify." },
  { slug: "iptv-generic-brand-names", re: /^(one|max|plus|pro|all|new|get|my|x|open|key|full|extra|easy|clean|family|media|room|world|global|euro|geo|sat|tele|canal|nord|sky|skyline|vision|edge|foster|formula|forum|hut|farm|revolution|high tech)\b|\b(one|max|plus|pro|world|global|worldwide|edge|sat|x|1|24|345|66|4u|4sat)\b|iptv(one|x|24|1|345|66|4u|4sat|plus|hut|farm|forum)|^la iptv|tvzon|coretv|evdtv|mitvpro|sstv|ok2|onpoint|briz|nap iptv|b1g|ib iptv|atv|nettv|unoiptv|ukiptv|tv team|tv plus|playiptv|livego|starshare|troypoint|bandwich|ipguys|gotit|gotv|eva\b|dmtn|iliria|e vision|fame|wise|lux|simple|xiptv|rediptv|roomiptv/i,
    label: "generic-word and short-name", sample: ["IPTV One", "My IPTV", "IPTV World"], title: "IPTV One, My IPTV, IPTV World & Short Names | MapleHD",
    intro: "Short, generic names (One, Max, Plus, World, Global, X) are common, which makes them hard to search for and easy to confuse with unrelated sites.", pattern: "When a name is a single common word, searching it returns a mix of unrelated apps, websites and resellers. Add the country or the word reviews to your search, and confirm the domain before you share any details." },
  { slug: "iptv-other-brand-names", re: /.*/, label: "other", sample: ["Smarters TV Pro", "Dream IPTV", "Blue TV IPTV"], title: "Smarters TV Pro & More IPTV Brand Names | MapleHD",
    intro: "This page covers the remaining names people search for. The same checklist applies to every one of them.", pattern: "The names here do not fit a single theme, and some are player apps rather than services. If you already have a subscription, you may only need a player: see the [IPTV apps hub](/iptv-apps)." },
];
export const groupFor = (kw) => BRAND_GROUPS.find((g) => g.re.test(kw)).slug;
