// Canada-specific angle pages: hockey/CFL, broadcasters, ISP comparisons, time zones, payment, holidays,
// winter/rural connectivity and extra device pages.
const FAQ_TRIAL = { q: "Can I test it before a big game?", a: "Yes. Request a [free trial](/free-trial) with no credit card and test the channel you need on your own devices and internet connection before game night." };

const team = ({ slug, name, kw, kws, anchor, region, regionSlug, feeds, note, cityLinks, hub = "iptv-nhl-canada", extraFaq }) => ({
  slug, cluster: "hockey", kind: "landing", hub, pillar: "iptv-nhl-canada",
  title: `IPTV ${name} — Watch Every Game | MapleHD`.slice(0, 60),
  desc: `Watch ${name} games with IPTV in Canada: sports channels, 4K, multi-screen and a free trial. Test on game night. Plans from $9/month, no contract.`.slice(0, 160),
  h1: `IPTV for ${name} Fans: How to Watch Every Game`,
  badge: `IPTV ${name} · NHL`,
  kw, kws, anchor,
  answer: `To watch the ${name} with IPTV, use a service that carries the sports channels holding the rights, ${feeds}. MapleHD includes Canadian sports channels, streams in HD and 4K and offers a free trial, so you can test a live ${name} game on your own connection first.`,
  sections: [
    { h: `Where ${name} games are shown`, p: [`${note} Broadcast rights are split between national and regional feeds and change between seasons, so always confirm the channel in your programme guide rather than assuming last year's setup.`], ul: [`Regional feed: ${feeds}`, "National windows: Sportsnet, CBC, TSN and other partners depending on the game", "Playoffs: coverage moves to national channels, so check the guide the day before"] },
    { h: "Game-night setup that works", ol: ["Test the channel in the guide before puck drop, not after.", "Use Ethernet or a strong Wi-Fi 5/6 connection on your main TV device.", "Enable hardware decoding in your [IPTV player](/iptv-player).", "Add the channel to favourites for one-press access.", "Keep a second device ready in case one stream needs a restart."] },
    { h: "Multi-screen and playoff nights", p: [`Playoff hockey often means two games at once. A plan with several connections lets you follow a second game on a phone or in another room. See [IPTV subscription plans](/iptv-subscription) for connection options, and our [Stanley Cup playoffs guide](/iptv-stanley-cup-playoffs) for more.`] },
    { h: `${name} fans by region`, p: [`${region} `, `Read the local guide: ${cityLinks}. You can also see how IPTV compares with a carrier TV bundle in [IPTV vs cable in Canada](/blog/iptv-vs-cable-canada).`] },
  ],
  faq: [
    { q: `Can I watch ${name} games on IPTV?`, a: `Yes, through the sports channels that hold the rights to the game. Check your player's programme guide and test the channel with a free trial.` },
    { q: `Which channel shows ${name} games?`, a: `Typically ${feeds}. Rights change between seasons, so confirm in the guide.` },
    { q: "Does IPTV work during playoffs?", a: "Yes, but demand is highest then. Use Ethernet, hardware decoding and start the stream early." },
    extraFaq,
    FAQ_TRIAL,
  ],
  related: [regionSlugFix(regionSlug), "iptv-sports", "iptv-4k", "iptv-time-zones-canada", "iptv-nhl-canada"],
});
function regionSlugFix(s) { return s; }

const broadcaster = ({ slug, name, kw, kws, anchor, owner, what, watch, faqQ, faqA }) => ({
  slug, cluster: "channels", kind: "guide", hub: "iptv-canadian-channels", pillar: "iptv-canadian-channels",
  title: `${name} on IPTV in Canada — How to Watch | MapleHD`.slice(0, 60),
  desc: `How to watch ${name} with IPTV in Canada: what the channel offers, regional feeds, HD and 4K options and how to check it on a free trial with MapleHD.`.slice(0, 160),
  h1: `${name} on IPTV: How to Watch in Canada`,
  badge: `${name} · IPTV Canada`,
  kw, kws, anchor,
  answer: `${name} is ${what}. With an IPTV service that carries it, you can watch ${name} live in your player app alongside thousands of other channels. MapleHD includes the major Canadian networks and offers a free trial so you can confirm the ${name} feed you need.`,
  sections: [
    { h: `About ${name}`, p: [`${name} is ${what}. ${owner}`] },
    { h: `What to watch on ${name}`, ul: watch },
    { h: `How to check ${name} on MapleHD`, ol: [`Open the [channel list](/channels-list) or search for ${name} in your player.`, "Choose the feed for your region if regional versions are listed.", "Test during a live programme on a busy evening.", "Add it to favourites for quick access."], p2: ["Local over-the-air stations can also be received with an antenna in many areas, which works well alongside an IPTV subscription."] },
    { h: "Related Canadian channel guides", p: ["See all [Canadian channels on IPTV](/iptv-canadian-channels), plus [CBC](/iptv-cbc), [CTV](/iptv-ctv), [Global](/iptv-global-tv), [TSN](/iptv-tsn) and [Sportsnet](/iptv-sportsnet), or start the [free trial](/free-trial)."] },
  ],
  faq: [
    { q: faqQ, a: faqA },
    { q: `Are regional ${name} feeds included?`, a: "MapleHD's lineup includes regional feeds for major channels where available. Check your programme guide for the feed for your province." },
    { q: `Can I watch ${name} in 4K?`, a: `Only where a 4K version of the feed exists. Most live channels are HD. See [4K IPTV](/iptv-4k) for requirements.` },
    FAQ_TRIAL,
  ],
  related: ["channels-list", "iptv-canada", "iptv-sports", "iptv-quebec"],
});

const isp = ({ slug, name, kw, kws, anchor, product, note, about, where }) => ({
  slug, cluster: "isp", kind: "compare", hub: "iptv-vs-cable-hub", pillar: "iptv-vs-cable-hub",
  title: `IPTV vs ${name} TV — Cost & Features Compared | MapleHD`.slice(0, 60),
  desc: `IPTV vs ${name} TV in Canada: how an IPTV subscription compares with ${product} on cost, contracts, devices and channels, and how to keep your internet.`.slice(0, 160),
  h1: `IPTV vs ${name} TV: What Canadians Should Compare`,
  badge: `IPTV vs ${name}`,
  kw, kws, anchor,
  answer: `IPTV is a TV subscription delivered over any internet connection, while ${product} is ${name}'s own TV bundle. Many Canadians keep their ${name} internet and replace only the TV bundle with an IPTV subscription such as MapleHD, which starts at $9/month with no contract.`,
  sections: [
    { h: `${name} TV vs IPTV at a glance`, table: { head: ["", `${product}`, "MapleHD IPTV"], rows: [["Needs the provider's internet?", note, "No, works over any good connection"], ["Contract", "Often a term or bundle discount", "None; prepaid plans"], ["Devices", "Provider box or app", "Firestick, Android TV, Smart TV, phone, PC"], ["Typical monthly cost", "Bundle-dependent, often $80+ with fees", "From $9"], ["On demand", "Included, provider library", "120,000+ titles"]] }, p2: ["Prices and packages change; check your current bill and the provider's current offers."] },
    { h: `About ${product}`, p: [about, where] },
    { h: "How to switch only the TV part", ol: ["Check whether your internet is sold separately from the TV bundle and what changes in price.", "Test IPTV first with a [free trial](/free-trial) while your current TV service is active.", "Confirm you have enough internet speed: about 15 Mbps per HD stream.", "Then downgrade or cancel the TV bundle, keeping the internet plan."] },
    { h: "What you might miss and what you gain", ul: ["Provider bundles may include set-top box features and support you are used to.", "IPTV can run on devices you already own and costs far less.", "IPTV depends entirely on your internet quality, so a stable connection matters."] },
    { h: "Related comparisons", p: ["See the [IPTV vs cable in Canada](/blog/iptv-vs-cable-canada) article and the other carrier comparisons in our [IPTV vs cable hub](/iptv-vs-cable-hub)."] },
  ],
  faq: [
    { q: `Can I use IPTV with ${name} internet?`, a: `Yes. IPTV works over any stable internet connection, including ${name}'s. You do not need ${name}'s TV service.` },
    { q: `Is IPTV cheaper than ${product}?`, a: `Usually by a wide margin. MapleHD starts at $9 per month, while carrier TV bundles often cost far more once fees are added. Check your own bill.` },
    { q: "Will I lose local channels?", a: "MapleHD includes major Canadian networks and regional sports channels. Check the [channel list](/channels-list) for your needs." },
    { q: "How much internet speed do I need?", a: "About 15 Mbps per HD stream and 25 Mbps per 4K stream, added up across simultaneous streams." },
    FAQ_TRIAL,
  ],
  related: ["blog/iptv-vs-cable-canada", "cheap-iptv-canada", "iptv-subscription", "iptv-canada"],
});

const device = ({ slug, kw, kws, anchor, title, desc, h1, badge, answer, sections, faq, related, hub = "iptv-devices" }) => ({
  slug, cluster: "devices", kind: "device", hub, title: title.slice(0, 60), desc: desc.slice(0, 160), h1, badge, kw, kws, anchor, answer, sections, faq, related,
});

export default [
  // ---------------- Hockey & CFL ----------------
  {
    slug: "iptv-nhl-canada", cluster: "hockey", kind: "hub", pillar: "iptv-sports", hub: "iptv-sports",
    title: "IPTV NHL Canada — Watch Every Canadian Team | MapleHD",
    desc: "Watch NHL hockey with IPTV in Canada: Leafs, Canadiens, Senators, Oilers, Flames, Canucks and Jets, plus playoffs, regional feeds and free trial. From $9.",
    h1: "IPTV for NHL Hockey in Canada: Every Canadian Team",
    badge: "IPTV NHL · Canada",
    kw: "iptv nhl canada", kws: ["watch nhl on iptv", "nhl iptv", "hockey iptv canada", "iptv hockey"],
    anchor: "IPTV for NHL hockey",
    answer: "Watching NHL hockey with IPTV means using a service that carries the sports channels showing Canadian teams, then testing a live game on your own connection. MapleHD includes Canadian sports channels and offers a free trial; the team pages below explain what to check for each club.",
    children: ["iptv-maple-leafs", "iptv-canadiens", "iptv-senators", "iptv-oilers", "iptv-flames", "iptv-canucks", "iptv-jets", "iptv-stanley-cup-playoffs", "iptv-cfl"],
    sections: [
      { h: "Canadian NHL teams", ul: ["[Toronto Maple Leafs](/iptv-maple-leafs)", "[Montréal Canadiens](/iptv-canadiens) ([en français](/fr/iptv-canadiens))", "[Ottawa Senators](/iptv-senators)", "[Edmonton Oilers](/iptv-oilers)", "[Calgary Flames](/iptv-flames)", "[Vancouver Canucks](/iptv-canucks)", "[Winnipeg Jets](/iptv-jets)"] },
      { h: "How regional and national hockey coverage works", p: ["Most regular-season games are shown on regional feeds that cover a team's home market, while national windows and the playoffs move to national channels. Rights are renegotiated periodically, so use your player's guide to confirm the channel."] },
      { h: "Before puck drop", ol: ["Test your stream with a free trial during a real game.", "Use Ethernet and hardware decoding.", "Choose a plan with enough connections for every screen.", "Save the channel as a favourite."] },
    ],
    faq: [
      { q: "Can I watch all Canadian NHL teams on IPTV?", a: "MapleHD includes Canadian sports channels that show Canadian teams' games. Confirm the feeds you need with a free trial." },
      { q: "Will there be blackouts?", a: "Blackout rules depend on the broadcaster and your location. Test the specific game feed and ask support if you see restrictions." },
      { q: "What speed do I need for hockey?", a: "About 15 Mbps for HD and 25 Mbps for 4K per stream. Wired connections handle fast puck movement best." },
      { q: "Is there French-language hockey coverage?", a: "Yes, French-language channels such as RDS and TVA Sports cover Canadiens games. See [Canadiens en français](/fr/iptv-canadiens)." },
    ],
    related: ["iptv-sports", "iptv-cfl", "iptv-ufc", "iptv-nba", "iptv-canadian-channels"],
  },
  team({ slug: "iptv-maple-leafs", name: "Toronto Maple Leafs", kw: "iptv maple leafs", kws: ["leafs iptv", "maple leafs iptv", "watch leafs games iptv", "leafs game today iptv"], anchor: "IPTV for Maple Leafs fans", region: "Leafs Nation stretches across Ontario and beyond, from the GTA to the Maritimes.", regionSlug: "iptv-gta", feeds: "Sportsnet and TSN regional feeds, with national games on Sportsnet and CBC", note: "Leafs coverage is spread across national and regional sports channels.", cityLinks: "[IPTV Toronto](/iptv-toronto), [IPTV Mississauga](/iptv-mississauga) and [IPTV Ontario](/iptv-ontario)", extraFaq: { q: "Can I watch Leafs games outside Ontario?", a: "Yes, with a stable connection anywhere in Canada. Check the guide for the feed available where you are." } }),
  team({ slug: "iptv-canadiens", name: "Montréal Canadiens", kw: "iptv canadiens", kws: ["canadiens iptv", "habs iptv", "montreal canadiens iptv", "watch habs games iptv"], anchor: "IPTV for Canadiens fans", region: "Habs fans span Québec and the rest of Canada, and many households want both French and English commentary.", regionSlug: "iptv-quebec", feeds: "RDS and TVA Sports for French, with English coverage on Sportsnet and TSN depending on the game", note: "French-language coverage is central to Canadiens broadcasts.", cityLinks: "[IPTV Montréal](/iptv-montreal), [IPTV Québec](/iptv-quebec) and [IPTV Laval](/iptv-laval)", extraFaq: { q: "Can I choose French or English commentary?", a: "Often yes, by choosing between the French and English feeds in your guide. Available options depend on the broadcaster and game." } }),
  team({ slug: "iptv-senators", name: "Ottawa Senators", kw: "iptv senators", kws: ["ottawa senators iptv", "sens iptv", "watch senators games iptv"], anchor: "IPTV for Senators fans", region: "Sens fans live across the National Capital Region on both sides of the Ottawa River.", regionSlug: "iptv-ottawa", feeds: "TSN regional feeds, with national games on Sportsnet and CBC", note: "Senators coverage is generally regional in the regular season.", cityLinks: "[IPTV Ottawa](/iptv-ottawa), [IPTV Gatineau](/iptv-gatineau) and [IPTV Kingston](/iptv-kingston)", extraFaq: { q: "Can Gatineau viewers watch in French?", a: "French-language options depend on the broadcaster. See [IPTV Gatineau](/iptv-gatineau) for local details." } }),
  team({ slug: "iptv-oilers", name: "Edmonton Oilers", kw: "iptv oilers", kws: ["edmonton oilers iptv", "oilers iptv", "watch oilers games iptv"], anchor: "IPTV for Oilers fans", region: "Oilers fans fill Edmonton, northern Alberta and the Territories.", regionSlug: "iptv-prairies", feeds: "Sportsnet's Oilers regional feed, with national games on Sportsnet and CBC", note: "Oilers games are a big draw during playoff runs.", cityLinks: "[IPTV Edmonton](/iptv-edmonton), [IPTV St. Albert](/iptv-st-albert) and [IPTV Alberta](/iptv-alberta)", extraFaq: { q: "Can I watch the Oilers in the Territories?", a: "Yes, if your connection has enough speed and data. See [IPTV Northern Canada](/iptv-northern-canada)." } }),
  team({ slug: "iptv-flames", name: "Calgary Flames", kw: "iptv flames", kws: ["calgary flames iptv", "flames iptv", "watch flames games iptv"], anchor: "IPTV for Flames fans", region: "Flames supporters cover Calgary, southern Alberta and parts of BC.", regionSlug: "iptv-prairies", feeds: "Sportsnet's Flames regional feed, with national games on Sportsnet and CBC", note: "The Battle of Alberta is the season's marquee fixture for many fans.", cityLinks: "[IPTV Calgary](/iptv-calgary), [IPTV Airdrie](/iptv-airdrie) and [IPTV Alberta](/iptv-alberta)", extraFaq: { q: "Can I watch Battle of Alberta games on two screens?", a: "Yes, with a multi-connection plan. Each stream uses one connection." } }),
  team({ slug: "iptv-canucks", name: "Vancouver Canucks", kw: "iptv canucks", kws: ["vancouver canucks iptv", "canucks iptv", "watch canucks games iptv"], anchor: "IPTV for Canucks fans", region: "Canucks fans stretch across British Columbia, from Metro Vancouver to the Island and Interior.", regionSlug: "iptv-lower-mainland", feeds: "Sportsnet's Pacific regional feed, with national games on Sportsnet and CBC", note: "Pacific Time means many home games start in the late afternoon or evening.", cityLinks: "[IPTV Vancouver](/iptv-vancouver), [IPTV Surrey](/iptv-surrey) and [IPTV British Columbia](/iptv-british-columbia)", extraFaq: { q: "What time do Canucks games start on the east coast?", a: "Pacific Time evening games often start late for Atlantic and Eastern viewers. See the [time zone guide](/iptv-time-zones-canada)." } }),
  team({ slug: "iptv-jets", name: "Winnipeg Jets", kw: "iptv jets", kws: ["winnipeg jets iptv", "jets iptv", "watch jets games iptv"], anchor: "IPTV for Jets fans", region: "Jets fans cover Manitoba and northwestern Ontario, with a legendary playoff atmosphere.", regionSlug: "iptv-prairies", feeds: "TSN's Jets regional feed, with national games on Sportsnet and CBC", note: "Winnipeg's whiteout playoff tradition has made Jets nights a community event.", cityLinks: "[IPTV Winnipeg](/iptv-winnipeg), [IPTV Brandon](/iptv-brandon) and [IPTV Manitoba](/iptv-manitoba)", extraFaq: { q: "Can I watch the Jets in Thunder Bay?", a: "Yes, with a stable connection. See [IPTV Thunder Bay](/iptv-thunder-bay)." } }),
  {
    slug: "iptv-stanley-cup-playoffs", cluster: "hockey", kind: "guide", hub: "iptv-nhl-canada", pillar: "iptv-nhl-canada",
    title: "IPTV Stanley Cup Playoffs Canada — Watch Guide | MapleHD",
    desc: "How to watch the Stanley Cup playoffs with IPTV in Canada: national channels, multi-game nights, setup checklist and tips to avoid buffering. Free trial.",
    h1: "IPTV Stanley Cup Playoffs: Watch Every Series in Canada",
    badge: "Stanley Cup Playoffs · IPTV",
    kw: "iptv stanley cup playoffs", kws: ["watch stanley cup playoffs iptv", "nhl playoffs iptv", "playoff hockey iptv"],
    anchor: "IPTV Stanley Cup playoffs",
    answer: "For IPTV during the Stanley Cup playoffs, national broadcasters carry most games, so check your programme guide for the channel each night and test the stream before puck drop. Use a wired connection, hardware decoding and a plan with enough connections for a second game.",
    sections: [
      { h: "Why playoffs are the hardest night for any stream", p: ["Playoff demand spikes across every provider and every home network. The two things you control are your local network (wired, uncongested) and your device settings (hardware decoding, adequate buffer)."] },
      { h: "Playoff checklist", ol: ["Two days before: test your main channel on a live game.", "Same day: restart the streaming device and router.", "30 minutes before: open the channel and confirm audio and video.", "During: keep a second device ready with the same channel.", "After: note any problems and message support with the time and channel."] },
      { h: "Watching two series at once", p: ["Double-header nights are common in the first round. A multi-connection plan lets you run one game on the TV and another on a tablet. See [IPTV plans](/iptv-subscription) and [IPTV NHL Canada](/iptv-nhl-canada)."] },
    ],
    faq: [
      { q: "Are Stanley Cup playoff games on IPTV?", a: "They are shown on national sports channels that an IPTV lineup can include. Confirm the channels with a free trial." },
      { q: "Why does my stream lag behind live during playoffs?", a: "Internet streams run a few seconds behind broadcast and can lag more under load. Wired connections reduce the delay." },
      { q: "Should I use 4K for the playoffs?", a: "Only if the feed is 4K and your speed is strong. HD is often steadier during peak demand." },
      FAQ_TRIAL,
    ],
    related: ["iptv-nhl-canada", "iptv-maple-leafs", "iptv-canadiens", "iptv-4k", "iptv-sports"],
  },
  {
    slug: "iptv-cfl", cluster: "hockey", kind: "guide", hub: "iptv-sports", pillar: "iptv-sports",
    title: "IPTV CFL Canada — Watch CFL Games & Grey Cup | MapleHD",
    desc: "Watch CFL football with IPTV in Canada: nine teams, Labour Day and Thanksgiving classics, the Grey Cup and how to test game-day streams. Free trial.",
    h1: "IPTV CFL: Watching the Canadian Football League",
    badge: "IPTV CFL · Grey Cup",
    kw: "iptv cfl", kws: ["cfl iptv", "watch cfl games iptv", "grey cup iptv", "cfl live stream canada"],
    anchor: "IPTV CFL",
    answer: "CFL games and the Grey Cup are shown on Canadian sports channels, which an IPTV lineup can include. Check the programme guide for each game's channel, test the stream on a real game day and use Ethernet for the steadiest picture.",
    sections: [
      { h: "CFL on Canadian sports channels", p: ["The CFL has nine teams across Canada, and games are shown on national sports channels with regional variations. Rights change over time, so confirm current channels in your guide."], ul: ["Regular-season games each week from summer into fall", "Labour Day and Thanksgiving weekend classics", "Division playoffs and the Grey Cup"] },
      { h: "CFL fans by region", p: ["See regional guides for [IPTV Saskatchewan](/iptv-saskatchewan) (Roughriders), [IPTV Manitoba](/iptv-manitoba) (Blue Bombers), [IPTV Alberta](/iptv-alberta) (Stampeders, Elks), [IPTV Hamilton](/iptv-hamilton) (Tiger-Cats), [IPTV Ottawa](/iptv-ottawa) (Redblacks), [IPTV Toronto](/iptv-toronto) (Argonauts) and [IPTV Vancouver](/iptv-vancouver) (BC Lions)."] },
      { h: "Game-day checklist", ol: ["Test the channel before kickoff.", "Use Ethernet and hardware decoding.", "Add the channel to favourites.", "Have a second device ready for stream restarts."] },
    ],
    faq: [
      { q: "Can I watch the Grey Cup on IPTV?", a: "The Grey Cup is shown on the national sports channels that hold the rights. Confirm the channel with a free trial." },
      { q: "Are all nine CFL teams covered?", a: "Games appear on the channels holding the rights; regional feeds may differ. Check the programme guide." },
      { q: "What speed do I need for football?", a: "About 15 Mbps per HD stream. Wired connections handle fast motion better." },
      FAQ_TRIAL,
    ],
    related: ["iptv-nhl-canada", "iptv-sports", "iptv-canadian-channels", "iptv-tsn"],
  },

  // ---------------- Broadcasters ----------------
  {
    slug: "iptv-canadian-channels", cluster: "channels", kind: "hub", pillar: "iptv-canada", hub: "iptv-canada",
    title: "Canadian Channels on IPTV — CBC, CTV, TSN & More | MapleHD",
    desc: "Canadian channels on IPTV: CBC, CTV, Global, City, TSN and Sportsnet, plus French-language networks. See what's included and how to check on a free trial.",
    h1: "Canadian Channels on IPTV: CBC, CTV, Global, TSN and Sportsnet",
    badge: "Canadian Channels · IPTV",
    kw: "canadian channels iptv", kws: ["canadian tv channels iptv", "iptv canadian channels", "watch canadian tv online"],
    anchor: "Canadian channels on IPTV",
    answer: "MapleHD's lineup includes major Canadian networks such as CBC, CTV, Global and City, sports channels such as TSN and Sportsnet, and French-language networks like TVA, RDS and Noovo. Use the guides below to see what each channel offers, and the free trial to confirm the feeds in your region.",
    children: ["iptv-cbc", "iptv-ctv", "iptv-global-tv", "iptv-tsn", "iptv-sportsnet", "iptv-quebec", "iptv-nhl-canada", "iptv-cfl"],
    sections: [
      { h: "Canadian networks", ul: ["[CBC](/iptv-cbc): public broadcaster with national and regional stations", "[CTV](/iptv-ctv): Bell Media's national network", "[Global](/iptv-global-tv): Corus's national network", "[TSN](/iptv-tsn) and [Sportsnet](/iptv-sportsnet): the two national sports networks"] },
      { h: "French-language channels", p: ["Québec and francophone viewers can find TVA, TVA Sports, RDS, Noovo and ICI Radio-Canada Télé. See [IPTV Québec](/iptv-quebec) and [IPTV en français](/fr)."] },
      { h: "Check the full list", p: ["The [channel list](/channels-list) shows what is included, and the [free trial](/free-trial) lets you confirm the regional feeds you need."] },
    ],
    faq: [
      { q: "Does MapleHD include Canadian channels?", a: "Yes, including major networks, sports channels and French-language channels. Check the channel list for details." },
      { q: "Are regional stations included?", a: "Regional feeds are included where available. Confirm your local station in the guide." },
      { q: "Can I watch Canadian TV outside Canada?", a: "Access when travelling depends on your connection and local restrictions. Contact support before you travel." },
      { q: "Is an antenna still useful?", a: "Yes. Local stations can often be received free over the air, which works well alongside IPTV." },
    ],
    related: ["channels-list", "iptv-canada", "iptv-sports", "iptv-quebec"],
  },
  broadcaster({ slug: "iptv-cbc", name: "CBC", kw: "iptv cbc", kws: ["cbc iptv", "watch cbc iptv", "cbc live iptv", "cbc hockey night in canada iptv"], anchor: "CBC on IPTV", what: "Canada's public broadcaster, with national television and regional stations across the country", owner: "It carries news, drama, documentaries and, with Sportsnet, Hockey Night in Canada.", watch: ["CBC News and local newscasts", "Hockey Night in Canada national games", "Canadian drama and comedy", "Documentaries and arts programming"], faqQ: "Can I watch CBC on IPTV?", faqA: "MapleHD's lineup includes CBC and its regional feeds where available. Check the programme guide for the station for your province." }),
  broadcaster({ slug: "iptv-ctv", name: "CTV", kw: "iptv ctv", kws: ["ctv iptv", "watch ctv iptv", "ctv live iptv"], anchor: "CTV on IPTV", what: "a national Canadian English-language network owned by Bell Media", owner: "It is known for national and local news, entertainment programming and sports simulcasts.", watch: ["CTV National News and local newscasts", "Popular US and Canadian entertainment series", "Major sports events", "Reality and talk shows"], faqQ: "Is CTV included in MapleHD?", faqA: "CTV and regional CTV stations are part of the lineup where available. Confirm your local station in the guide." }),
  broadcaster({ slug: "iptv-global-tv", name: "Global TV", kw: "iptv global tv", kws: ["global tv iptv", "watch global tv iptv", "global news iptv"], anchor: "Global TV on IPTV", what: "a national Canadian English-language network owned by Corus Entertainment", owner: "It offers Global News, Canadian and US series and reality programming.", watch: ["Global News and local newscasts", "US network series", "Reality and competition shows", "Weekend movies"], faqQ: "Can I watch Global TV on IPTV?", faqA: "Global and its regional stations are part of the lineup where available. Check the guide for your province." }),
  broadcaster({ slug: "iptv-tsn", name: "TSN", kw: "iptv tsn", kws: ["tsn iptv", "watch tsn iptv", "tsn1 tsn2 tsn3 tsn4 tsn5 iptv", "tsn live iptv"], anchor: "TSN on IPTV", what: "Canada's national sports network, with several channels (TSN1 to TSN5) and regional feeds", owner: "It is owned by Bell Media and shows hockey, football, basketball, motorsport and more.", watch: ["NHL regional feeds such as Jets and Senators games", "CFL football and the Grey Cup", "Motorsport and international events", "Sports news and analysis"], faqQ: "Which TSN channels does MapleHD include?", faqA: "MapleHD's lineup includes TSN channels and regional feeds where available. See the [channel list](/channels-list) and confirm a live game with the free trial." }),
  broadcaster({ slug: "iptv-sportsnet", name: "Sportsnet", kw: "iptv sportsnet", kws: ["sportsnet iptv", "watch sportsnet iptv", "sportsnet live iptv", "sportsnet now iptv"], anchor: "Sportsnet on IPTV", what: "Canada's national sports network from Rogers, with national channels and regional feeds", owner: "It shows NHL hockey (with CBC's Hockey Night in Canada), MLB, NBA and more.", watch: ["NHL regional feeds for Oilers, Flames and Canucks", "Hockey Night in Canada national games", "MLB and NBA coverage", "Sports news and talk"], faqQ: "Is Sportsnet included in MapleHD?", faqA: "Sportsnet channels and regional feeds are part of the lineup where available. Confirm your regional feed in the guide." }),

  // ---------------- ISP comparisons ----------------
  {
    slug: "iptv-vs-cable-hub", cluster: "isp", kind: "hub", pillar: "blog/iptv-vs-cable-canada", hub: "iptv-canada",
    title: "IPTV vs Bell, Rogers, Telus, Shaw & Vidéotron TV | MapleHD",
    desc: "Compare IPTV with Bell Fibe TV, Rogers Ignite TV, Telus TV, Shaw and Vidéotron Helix: cost, contracts, devices and how to keep your internet.",
    h1: "IPTV vs Canadian Carrier TV: Bell, Rogers, Telus, Shaw and Vidéotron",
    badge: "IPTV vs Carrier TV",
    kw: "iptv vs cable canada providers", kws: ["iptv vs bell", "iptv vs rogers", "iptv vs telus", "cable alternatives canada"],
    anchor: "IPTV vs carrier TV",
    answer: "You can keep your internet from Bell, Rogers, Telus, Shaw or Vidéotron and replace only the TV bundle with an IPTV subscription. IPTV works over any good connection, costs from $9/month with MapleHD and has no contract. These pages compare each carrier's TV product with IPTV.",
    children: ["iptv-vs-bell", "iptv-vs-rogers", "iptv-vs-telus", "iptv-vs-shaw", "iptv-vs-videotron", "blog/iptv-vs-cable-canada"],
    sections: [
      { h: "Which comparison to read", ul: ["[IPTV vs Bell Fibe TV](/iptv-vs-bell)", "[IPTV vs Rogers Ignite TV](/iptv-vs-rogers)", "[IPTV vs Telus TV](/iptv-vs-telus)", "[IPTV vs Shaw TV](/iptv-vs-shaw)", "[IPTV vs Vidéotron Helix](/iptv-vs-videotron)"] },
      { h: "The common approach", p: ["Most people who switch keep their internet plan, check the price change if the TV bundle is removed, test IPTV with a free trial, and then cancel the TV package. Speed matters: about 15 Mbps per HD stream."] },
    ],
    faq: [
      { q: "Can I keep my internet and drop cable TV?", a: "Usually yes. Ask your provider what the internet-only price is, then compare it with IPTV." },
      { q: "Is IPTV cheaper than my carrier's TV?", a: "Typically much cheaper, but compare against your own bill." },
      { q: "Does IPTV work on Bell, Rogers, Telus, Shaw and Vidéotron internet?", a: "Yes. IPTV works over any stable internet connection." },
      FAQ_TRIAL,
    ],
    related: ["cheap-iptv-canada", "iptv-canada", "iptv-subscription"],
  },
  isp({ slug: "iptv-vs-bell", name: "Bell", kw: "iptv vs bell fibe", kws: ["bell fibe tv alternative", "iptv vs bell", "replace bell tv", "bell fibe tv cost"], anchor: "IPTV vs Bell Fibe TV", product: "Bell Fibe TV", note: "Fibe TV is sold with Bell internet", about: "Bell is one of Canada's national carriers. Its TV product, Fibe TV, is sold with Bell internet and delivered through a set-top box and the Fibe TV app, and Bell Media owns channels such as CTV and TSN.", where: "Bell service is strongest in Ontario, Québec and Atlantic Canada. Because Bell owns sports and news networks, some viewers want to keep those channels; check that the specific channels you need are in your IPTV lineup before cancelling." }),
  isp({ slug: "iptv-vs-rogers", name: "Rogers", kw: "iptv vs rogers ignite", kws: ["rogers ignite tv alternative", "iptv vs rogers", "replace rogers tv", "rogers ignite tv cost"], anchor: "IPTV vs Rogers Ignite TV", product: "Rogers Ignite TV", note: "Ignite TV is sold with Rogers internet", about: "Rogers is a national carrier whose TV product, Ignite TV, is sold with Rogers internet and uses the Ignite TV box and app. Rogers also owns Sportsnet, and Shaw is now part of Rogers.", where: "Rogers is strongest in Ontario, the Atlantic provinces and, with Shaw, Western Canada. Many customers keep Rogers internet, which suits IPTV, and drop only the TV package." }),
  isp({ slug: "iptv-vs-telus", name: "Telus", kw: "iptv vs telus tv", kws: ["telus tv alternative", "iptv vs telus", "replace telus tv", "telus optik tv alternative"], anchor: "IPTV vs Telus TV", product: "Telus TV (formerly Optik TV)", note: "Telus TV is sold with Telus internet", about: "Telus is a major carrier in Western Canada. Its TV service, formerly Optik TV, is sold with Telus internet and available on a set-top box or app.", where: "Telus service is strongest in British Columbia and Alberta, with fibre in many neighbourhoods. Telus fibre suits IPTV well, so many households keep the internet and replace only the TV bundle." }),
  isp({ slug: "iptv-vs-shaw", name: "Shaw", kw: "iptv vs shaw tv", kws: ["shaw tv alternative", "iptv vs shaw", "replace shaw tv", "shaw cable alternative"], anchor: "IPTV vs Shaw TV", product: "Shaw's TV service (now part of Rogers)", note: "Shaw TV was sold with Shaw internet; the company is now part of Rogers", about: "Shaw was Western Canada's cable and internet provider and is now part of Rogers. Its TV service was offered with Shaw internet through set-top boxes and apps.", where: "If you are on a Shaw plan, check with Rogers what changes apply to your account. IPTV works over Shaw or Rogers internet in the same way, so you can compare your TV bundle price with an IPTV plan." }),
  isp({ slug: "iptv-vs-videotron", name: "Vidéotron", kw: "iptv vs videotron helix", kws: ["videotron helix alternative", "iptv vs videotron", "remplacer videotron tv", "illico alternative"], anchor: "IPTV vs Vidéotron Helix", product: "Vidéotron Helix and illico TV", note: "Helix is sold with Vidéotron internet", about: "Vidéotron is Québec's leading cable and internet provider. Its Helix platform combines TV, internet and a smart-home ecosystem, with French-language channels central to the lineup.", where: "Vidéotron is strongest in Québec. Francophone households should check that the French-language channels they use, such as TVA, RDS and Noovo, are in the IPTV lineup; see [IPTV Québec](/iptv-quebec) and [IPTV en français](/fr)." }),

  // ---------------- Practical Canada pages ----------------
  {
    slug: "iptv-time-zones-canada", cluster: "practical", kind: "guide", hub: "iptv-canada", pillar: "iptv-canada",
    title: "IPTV Time Zones in Canada — Game Times & EPG | MapleHD",
    desc: "How Canada's six time zones affect IPTV: programme guide (EPG) times, NHL start times by province and how to fix a guide showing the wrong time.",
    h1: "Canadian Time Zones and Your IPTV Programme Guide",
    badge: "Time Zones · EPG · Canada",
    kw: "iptv time zones canada", kws: ["iptv epg time zone", "iptv guide wrong time", "nhl game times canada time zones"],
    anchor: "IPTV time zones in Canada",
    answer: "Canada has six time zones, and your IPTV programme guide (EPG) shows times in your device's time zone. If shows or games look hours off, set your device to the correct time zone and refresh the guide in your player.",
    sections: [
      { h: "Canada's six time zones", table: { head: ["Zone", "Example places", "Offset note"], rows: [["Pacific", "Vancouver, Victoria", "Three hours behind Atlantic"], ["Mountain", "Calgary, Edmonton, Yellowknife", "Yukon stays on this time all year"], ["Central", "Winnipeg, Regina", "Saskatchewan stays on Central Standard Time all year"], ["Eastern", "Toronto, Ottawa, Montréal", "Most of the population"], ["Atlantic", "Halifax, Moncton, Charlottetown", "One hour ahead of Eastern"], ["Newfoundland", "St. John's", "Half an hour ahead of Atlantic"]] } },
      { h: "Converting a game time", p: ["A 7:00 p.m. Eastern start is 4:00 p.m. Pacific, 5:00 p.m. Mountain, 6:00 p.m. Central, 8:00 p.m. Atlantic and 8:30 p.m. in Newfoundland. Because Saskatchewan and Yukon don't change clocks, their offset to other provinces changes with daylight saving time."] },
      { h: "Fix a guide showing the wrong time", ol: ["Set your device's time zone and turn on automatic time.", "In your player, refresh the guide (EPG) and check any time offset setting.", "Reopen the player and check a channel you know.", "If it is still wrong, contact support with the channel name and what you see."] },
      { h: "Time zone guides for your province", p: ["See [IPTV Ontario](/iptv-ontario), [IPTV British Columbia](/iptv-british-columbia), [IPTV Saskatchewan](/iptv-saskatchewan) and [IPTV Newfoundland and Labrador](/iptv-newfoundland-and-labrador), or the [IPTV by city](/iptv-cities) directory."] },
    ],
    faq: [
      { q: "Why is my IPTV guide showing the wrong time?", a: "The guide uses your device's time zone. Set the correct zone, turn on automatic time and refresh the guide in your player." },
      { q: "How many time zones does Canada have?", a: "Six: Pacific, Mountain, Central, Eastern, Atlantic and Newfoundland." },
      { q: "Do Saskatchewan and Yukon change their clocks?", a: "No. They stay on the same time all year, so their offset to other provinces changes with daylight saving time." },
      { q: "What time is an Eastern evening game on the west coast?", a: "Three hours earlier: a 7:00 p.m. Eastern game starts at 4:00 p.m. Pacific." },
    ],
    related: ["iptv-cities", "iptv-nhl-canada", "iptv-dvr-catch-up", "iptv-canada"],
  },
  {
    slug: "iptv-payment-canada", cluster: "practical", kind: "guide", hub: "iptv-canada", pillar: "iptv-subscription",
    title: "Pay for IPTV in Canada — CAD & Interac | MapleHD",
    desc: "How to pay for IPTV in Canada: prices in Canadian dollars, Interac e-Transfer and other methods, payment safety tips, and MapleHD's refund policy.",
    h1: "Paying for IPTV in Canada: CAD Pricing and Interac e-Transfer",
    badge: "IPTV Payment · CAD · Interac",
    kw: "iptv interac e-transfer", kws: ["pay for iptv canada", "iptv cad pricing", "iptv payment methods canada", "buy iptv interac"],
    anchor: "paying for IPTV in Canada",
    answer: "When you pay for IPTV with MapleHD, prices are in Canadian dollars, and you can pay by Interac e-Transfer or the other methods shown on the order form. Plans start at $9/month and are prepaid with no contract, so you know exactly what you are paying before you order.",
    sections: [
      { h: "Prices in Canadian dollars", table: { head: ["Plan (1 device)", "Price"], rows: [["1 month", "$9"], ["3 months", "$29"], ["6 months", "$39"], ["12 months", "$49"]] }, p2: ["More connections cost more. See the [pricing page](/pricing) for every combination."] },
      { h: "Paying by Interac e-Transfer", ol: ["Choose your plan and fill in the order form.", "Follow the payment instructions shown after ordering.", "Send the Interac e-Transfer from your bank.", "Your login details are emailed after payment is confirmed, usually within minutes."] },
      { h: "Payment safety tips", ul: ["Only pay through details shown on the official order flow.", "Be wary of anyone who contacts you first and asks for payment.", "Keep your receipt and order email.", "Read the [refund policy](/refund-policy) and [terms](/terms-of-service) before paying."] },
    ],
    faq: [
      { q: "Does MapleHD accept Interac e-Transfer?", a: "Yes. Interac e-Transfer is one of the accepted payment methods; the order form shows current options." },
      { q: "Are prices in Canadian dollars?", a: "Yes. All prices on the site are in Canadian dollars." },
      { q: "Is there a contract?", a: "No. Plans are prepaid for the duration you choose." },
      { q: "How fast do I get my login after paying?", a: "Usually within minutes of payment confirmation. Contact support if you have not received it." },
    ],
    related: ["pricing", "iptv-subscription", "cheap-iptv-canada", "refund-policy", "free-trial"],
  },
  {
    slug: "iptv-canadian-holidays", cluster: "practical", kind: "guide", hub: "iptv-canada", pillar: "iptv-canada",
    title: "IPTV for Canadian Holidays — Canada Day & More | MapleHD",
    desc: "Plan your holiday viewing in Canada: Canada Day, Victoria Day, Thanksgiving, Remembrance Day and Boxing Day sports and TV, and how to prepare your IPTV.",
    h1: "IPTV for Canadian Holidays: Canada Day, Thanksgiving, Boxing Day and More",
    badge: "Canadian Holidays · IPTV",
    kw: "iptv canadian holidays", kws: ["canada day iptv", "boxing day iptv", "thanksgiving cfl iptv", "victoria day iptv", "holiday tv canada"],
    anchor: "IPTV for Canadian holidays",
    answer: "IPTV for Canadian holidays means preparing for big viewing moments: Canada Day celebrations, Victoria Day weekend playoffs, Thanksgiving CFL football and Boxing Day hockey and basketball. Prepare by testing your streams early, using Ethernet and choosing a plan with enough connections for a full house.",
    sections: [
      { h: "Holiday viewing calendar", table: { head: ["Holiday", "When", "Typical viewing"], rows: [["Victoria Day", "Monday before May 25", "Stanley Cup and NBA playoffs, long-weekend movies"], ["Canada Day", "July 1", "National celebrations and fireworks broadcasts"], ["Labour Day", "First Monday of September", "CFL Labour Day classics"], ["Thanksgiving", "Second Monday of October", "CFL Thanksgiving weekend and NFL"], ["Remembrance Day", "November 11", "Ceremonies and documentaries"], ["Boxing Day", "December 26", "Hockey, basketball and the world junior hockey tournament"]] }, p2: ["Dates and schedules change by year; check your programme guide."] },
      { h: "Prepare your IPTV for a full house", ol: ["Test your main channels a few days early.", "Restart your streaming devices and router the day before.", "Use Ethernet on the main TV.", "Check you have enough connections for every screen.", "Save the sports and news channels you need as favourites."] },
      { h: "Family viewing tips", ul: ["Use the [free trial](/free-trial) to check streams before guests arrive.", "Add kids' channels and on-demand titles for quiet time: see [IPTV VOD](/iptv-vod-movies-series).", "Use [catch-up](/iptv-dvr-catch-up) for programmes you miss."] },
    ],
    faq: [
      { q: "Can I watch Canada Day broadcasts on IPTV?", a: "National celebration broadcasts appear on Canadian networks such as CBC and CTV. Check the programme guide for the schedule." },
      { q: "Can I watch the CFL on Thanksgiving?", a: "CFL holiday games are shown on Canadian sports channels. See [IPTV CFL](/iptv-cfl)." },
      { q: "What is on IPTV on Boxing Day?", a: "Hockey, basketball and the world junior tournament appear on Canadian sports channels. Check the guide for details." },
      { q: "How many devices can watch at once?", a: "It depends on your plan's connections (1 to 10). See [pricing](/pricing)." },
    ],
    related: ["iptv-cfl", "iptv-nhl-canada", "iptv-sports", "iptv-deals", "iptv-subscription"],
  },
  {
    slug: "iptv-winter-buffering", cluster: "practical", kind: "guide", hub: "iptv-canada", pillar: "iptv-canada",
    title: "IPTV Buffering in Winter — Canadian Fixes That Work | MapleHD",
    desc: "Why IPTV buffers in Canadian winters and how to fix it: cold devices, Wi-Fi congestion, storms, ISP peaks and settings that keep hockey nights smooth.",
    h1: "Fix IPTV Buffering in Canadian Winters",
    badge: "Winter Buffering · Fixes",
    kw: "iptv buffering winter", kws: ["iptv buffering canada", "why does iptv buffer at night", "iptv freezing during storms", "fix iptv buffering"],
    anchor: "IPTV winter buffering fixes",
    answer: "IPTV buffering in winter usually comes from more people online in the evening, congested Wi-Fi, storm-damaged lines or a device that is overworked. Use Ethernet, restart the device and router, enable hardware decoding and lower the stream quality if your speed drops at night.",
    sections: [
      { h: "Why buffering rises in winter", ul: ["More people are home streaming in the evening, so neighbourhood networks are busier.", "Cold weather and ice can damage outdoor lines and equipment.", "Heating and appliances can add Wi-Fi interference.", "Older devices struggle with 4K when they are also running many apps."] },
      { h: "Step-by-step fixes", ol: ["Test speed on the streaming device itself at peak time.", "Switch from Wi-Fi to Ethernet, or move the router closer.", "Restart the router and the device.", "Turn on hardware decoding and set a medium or large buffer.", "Choose HD instead of 4K during peak evening hours.", "If it persists, contact your internet provider and then support with the channel and time."] },
      { h: "Storm and outage plan", p: ["Keep a phone hotspot as a backup, know where your router is and unplug and re-plug it after a power outage. See our [4K IPTV guide](/iptv-4k) for device settings and the [rural internet guide](/iptv-rural-canada) if your connection is limited."] },
    ],
    faq: [
      { q: "Why does my IPTV buffer at night?", a: "Evening is peak time on most home and neighbourhood networks. Use Ethernet, lower quality and check your speed at that time." },
      { q: "Can cold weather affect IPTV?", a: "Cold can damage outdoor lines or equipment, and storms can cause outages. Indoors, keep devices ventilated and away from heat sources." },
      { q: "Will a VPN fix buffering?", a: "Usually not, and it can slow things down. Fix the network first." },
      { q: "Should I use 4K in winter?", a: "Use 4K only if your speed holds at peak time; otherwise HD is steadier." },
    ],
    related: ["iptv-rural-canada", "iptv-4k", "iptv-server", "iptv-customer-service", "iptv-cities"],
  },
  {
    slug: "iptv-rural-canada", cluster: "practical", kind: "guide", hub: "iptv-canada", pillar: "iptv-canada",
    title: "IPTV in Rural Canada — Slow Internet Tips | MapleHD",
    desc: "IPTV on rural and small-town internet in Canada: how much speed you need, fixed wireless, satellite and LTE limits, data caps and settings that work.",
    h1: "IPTV in Rural Canada: Making It Work on Slower Internet",
    badge: "Rural IPTV · Canada",
    kw: "iptv rural canada", kws: ["iptv slow internet canada", "iptv satellite internet", "iptv low bandwidth", "iptv data usage canada"],
    anchor: "IPTV in rural Canada",
    answer: "IPTV works in rural Canada if you have about 5 to 8 Mbps for a low-quality stream and about 15 Mbps for HD. On slower, capped or satellite connections, choose lower quality, avoid multiple simultaneous streams and check your data allowance before subscribing.",
    sections: [
      { h: "Speeds that work", table: { head: ["Quality", "Suggested speed per stream", "Approx. data per hour"], rows: [["SD / low", "3 to 5 Mbps", "1 to 2 GB"], ["HD", "15 Mbps", "About 3 GB or more"], ["4K", "25 Mbps", "10 GB or more"]] }, p2: ["Figures are estimates; real usage varies by channel and player settings."] },
      { h: "Rural connection types", ul: ["Fixed wireless: can be good, but congestion at peak times may reduce speeds.", "Satellite (including low-orbit services where available): improving, but data policies vary.", "LTE/5G home internet: watch data allowances.", "DSL: speed drops with distance from the exchange."] },
      { h: "Settings for slower connections", ol: ["Choose SD or HD, not 4K.", "Increase the player's buffer size.", "Avoid several streams at once; buy only the connections you need.", "Use a wired connection to the router if possible.", "Test at peak evening time with the [free trial](/free-trial) before subscribing."] },
      { h: "Northern and remote communities", p: ["See [IPTV Northern Canada](/iptv-northern-canada), [IPTV Yukon](/iptv-yukon), [IPTV Northwest Territories](/iptv-northwest-territories) and [IPTV Nunavut](/iptv-nunavut) for regional notes, and the [winter buffering guide](/iptv-winter-buffering)."] },
    ],
    faq: [
      { q: "How much internet speed do I need for IPTV?", a: "About 15 Mbps per HD stream and 25 Mbps for 4K. Lower quality streams can work on 3 to 5 Mbps." },
      { q: "Does IPTV work on satellite internet?", a: "It can, subject to speed, latency and data allowance. Test with a trial and use lower quality." },
      { q: "How much data does IPTV use?", a: "HD can use about 3 GB per hour or more, and 4K far more. Check your data plan." },
      { q: "Can I use IPTV on mobile data at home?", a: "Yes, but watch your data allowance. HD and 4K use a lot." },
    ],
    related: ["iptv-winter-buffering", "iptv-northern-canada", "iptv-4k", "iptv-cities", "free-trial"],
  },

  // ---------------- Devices ----------------
  device({
    slug: "iptv-fire-tv-stick-4k-max", kw: "iptv fire tv stick 4k max", kws: ["iptv firestick 4k max", "firestick 4k max iptv", "fire tv stick 4k iptv", "best firestick for iptv"], anchor: "IPTV on Fire TV Stick 4K Max",
    title: "IPTV on Fire TV Stick 4K & 4K Max — Setup | MapleHD", desc: "IPTV on the Fire TV Stick 4K and 4K Max in Canada: why they suit IPTV, differences from the Lite, setup with TiviMate or Smarters and 4K settings.", h1: "IPTV on Fire TV Stick 4K and 4K Max", badge: "Fire TV Stick 4K · 4K Max",
    answer: "The Fire TV Stick 4K and 4K Max are the best Firesticks for IPTV: they decode 4K, handle large channel lists and run TiviMate and IPTV Smarters Pro smoothly. Install a player, add your MapleHD Xtream Codes login and use Ethernet or strong Wi-Fi for live sport.",
    sections: [
      { h: "Fire TV Stick models compared", table: { head: ["Model", "Best for", "Notes"], rows: [["Fire TV Stick 4K Max", "Heavy users, 4K, large guides", "Fastest of the range with newer Wi-Fi"], ["Fire TV Stick 4K", "Most homes", "4K support at a lower price"], ["Fire TV Stick Lite", "HD only, basic use", "See [Lite guide](/iptv-fire-tv-stick-lite)"]] }, p2: ["Specifications change by generation; check the current listing."] },
      { h: "Setup steps", ol: ["Connect the stick to an HDMI 2.0 port and finish Amazon's setup.", "Install Downloader and allow installs from it.", "Install [TiviMate](/tivimate-firestick) or [IPTV Smarters Pro](/iptv-smarters-pro-firestick).", "Enter your Xtream Codes login and load channels."] },
      { h: "Settings for smooth 4K", ul: ["Use an Ethernet adapter where you can.", "Turn on hardware decoding in the player.", "Restart the stick weekly and clear the app cache.", "Keep at least 25 Mbps free per 4K stream."] },
    ],
    faq: [
      { q: "Which Fire TV Stick is best for IPTV?", a: "The Fire TV Stick 4K Max is the best all-round choice. The 4K model is also good." },
      { q: "Does the Fire TV Stick 4K support 4K IPTV?", a: "Yes, on 4K streams with a 4K TV and enough bandwidth." },
      { q: "Can I use Ethernet with a Firestick?", a: "Yes, with a compatible Ethernet adapter." },
      { q: "Where is the full setup guide?", a: "See [IPTV on Firestick](/iptv-firestick-canada) and [best IPTV for Firestick](/best-iptv-for-firestick)." },
    ],
    related: ["iptv-firestick-canada", "best-iptv-for-firestick", "iptv-fire-tv-stick-lite", "tivimate-firestick", "iptv-4k"],
  }),
  device({
    slug: "iptv-fire-tv-stick-lite", kw: "iptv fire tv stick lite", kws: ["firestick lite iptv", "fire stick lite iptv", "fire tv lite iptv"], anchor: "IPTV on Fire TV Stick Lite",
    title: "IPTV on Fire TV Stick Lite — Is It Good Enough? | MapleHD", desc: "Can you use IPTV on a Fire TV Stick Lite? Yes for HD. See limits versus 4K models, best apps, settings for smooth playback and when to upgrade.", h1: "IPTV on Fire TV Stick Lite: What to Expect", badge: "Fire TV Stick Lite",
    answer: "The Fire TV Stick Lite works for IPTV in HD: install TiviMate or IPTV Smarters Pro through Downloader and add your MapleHD login. It has no 4K and less headroom, so large guides can feel slower; upgrade to a 4K or 4K Max stick if you want 4K or smoother navigation.",
    sections: [
      { h: "What the Lite does well", ul: ["HD live TV and on-demand titles", "Low cost and easy to move between TVs", "Runs the same IPTV players as other Firesticks"] },
      { h: "Limits to know", ul: ["No 4K playback, so 4K channels play in HD or not at all.", "Less memory, so large channel lists and guides can lag.", "Basic remote without TV controls on some versions."], p2: ["For the best experience see [Fire TV Stick 4K and 4K Max](/iptv-fire-tv-stick-4k-max)."] },
      { h: "Tips for smooth playback", ol: ["Keep the guide (EPG) small by hiding unused categories.", "Clear the player cache and restart weekly.", "Use a wired adapter or a strong 5 GHz connection.", "Set the player to HD and enable hardware decoding."] },
    ],
    faq: [
      { q: "Does IPTV work on the Fire TV Stick Lite?", a: "Yes, in HD. Install a player like TiviMate or IPTV Smarters Pro." },
      { q: "Can the Lite play 4K IPTV?", a: "No. It is an HD device. Use a 4K or 4K Max model for 4K." },
      { q: "Why is my Lite slow with IPTV?", a: "Limited memory and a large guide are common causes. Hide unused categories and clear the cache." },
      { q: "Should I upgrade?", a: "If you want 4K or smoother navigation, yes. See [Firestick options](/best-iptv-for-firestick)." },
    ],
    related: ["iptv-fire-tv-stick-4k-max", "iptv-firestick-canada", "tivimate-firestick", "iptv-smarters-pro-firestick", "iptv-4k"],
  }),
  device({
    slug: "iptv-tcl-tv", kw: "iptv tcl tv", kws: ["tcl google tv iptv", "tcl roku tv iptv", "iptv on tcl"], anchor: "IPTV on TCL TV",
    title: "IPTV on TCL TV (Google TV & Roku TV) | MapleHD Canada", desc: "How to watch IPTV on a TCL TV in Canada: Google TV models run TiviMate and Smarters, Roku TV models need workarounds. Setup steps for MapleHD.", h1: "IPTV on TCL TVs: Google TV and Roku TV Models", badge: "IPTV · TCL TV",
    answer: "TCL sells both Google TV and Roku TV models in Canada. On a Google TV model, install TiviMate or IPTV Smarters Pro from Google Play and add your MapleHD login. On a Roku TV model, use a Firestick or Android box on an HDMI port, or cast from a supported phone app.",
    sections: [
      { h: "Which TCL do you have?", table: { head: ["TCL model type", "IPTV approach"], rows: [["Google TV", "Install [TiviMate](/tivimate) or [IPTV Smarters](/iptv-smarters) from Google Play"], ["Roku TV", "Add a [Firestick](/iptv-firestick-canada) or Android box; see [IPTV on Roku](/iptv-roku-canada)"]] } },
      { h: "Setup on TCL Google TV", ol: ["Open Google Play on the TV and search for your player.", "Install it and choose Xtream Codes login.", "Enter your MapleHD server, username and password.", "Set favourites and enable hardware decoding."] },
      { h: "Tips", ul: ["Use Ethernet for 4K and live sport.", "Keep the TV software updated.", "If the built-in app lags, an external device may be smoother."], p2: ["Other brands: [Sony and Hisense](/iptv-sony-hisense-tv), [Samsung](/iptv-samsung-tv-canada) and [LG](/iptv-lg-tv-canada)."] },
    ],
    faq: [
      { q: "Can I watch IPTV on a TCL TV?", a: "Yes. Google TV models run IPTV apps directly; Roku TV models need an external device or casting." },
      { q: "How do I know if my TCL is Google TV or Roku TV?", a: "Check the home screen and the model listing. Google TV shows Google's interface; Roku TV shows Roku's tiles." },
      { q: "What is the best app for TCL Google TV?", a: "TiviMate or IPTV Smarters Pro." },
      { q: "Does 4K work on TCL?", a: "Yes on 4K models with a 4K source and enough bandwidth." },
    ],
    related: ["iptv-google-tv", "iptv-roku-canada", "iptv-smart-tv-canada", "iptv-sony-hisense-tv", "iptv-devices"],
  }),
  device({
    slug: "iptv-google-tv", kw: "iptv google tv", kws: ["google tv iptv app", "best iptv for google tv", "iptv on google tv", "chromecast with google tv iptv"], anchor: "IPTV on Google TV",
    title: "IPTV on Google TV — Best Apps & Setup Guide | MapleHD", desc: "Set up IPTV on Google TV in Canada: Sony, TCL, Hisense, Nvidia Shield and Chromecast with Google TV. Best apps, settings and fixes for MapleHD.", h1: "IPTV on Google TV: Sony, TCL, Hisense, Shield and Chromecast", badge: "IPTV · Google TV",
    answer: "Google TV (and Android TV) devices run IPTV apps directly. Install TiviMate or IPTV Smarters Pro from Google Play, choose Xtream Codes login and enter your MapleHD details. This works on Sony, TCL and Hisense TVs, the Nvidia Shield and Chromecast with Google TV.",
    sections: [
      { h: "Google TV devices that work", ul: ["Sony Google TV models: see [Sony and Hisense](/iptv-sony-hisense-tv)", "TCL Google TV models: see [TCL](/iptv-tcl-tv)", "Hisense Google TV models", "[Nvidia Shield](/iptv-nvidia-shield)", "[Chromecast with Google TV](/iptv-chromecast)"] },
      { h: "Best IPTV apps for Google TV", p: ["TiviMate has the most TV-friendly guide; IPTV Smarters Pro is free and familiar; XCIPTV and OTT Navigator add options. Compare them on the [IPTV apps hub](/iptv-apps)."] },
      { h: "Setup steps", ol: ["Open Google Play and install your chosen player.", "Add your MapleHD Xtream Codes login.", "Let the guide sync, then set favourites.", "Enable hardware decoding for 4K."] },
    ],
    faq: [
      { q: "What is the difference between Android TV and Google TV?", a: "Google TV is the newer interface built on Android TV. Both run the same IPTV apps." },
      { q: "Which app is best for Google TV?", a: "TiviMate is popular, and IPTV Smarters Pro is a good free choice." },
      { q: "Can I use Chromecast with Google TV for IPTV?", a: "Yes. It installs apps directly." },
      { q: "Do I need a VPN?", a: "No. A VPN is not required to use MapleHD." },
    ],
    related: ["iptv-android-tv-canada", "iptv-nvidia-shield", "iptv-tcl-tv", "iptv-sony-hisense-tv", "best-android-tv-box", "tivimate"],
  }),
  device({
    slug: "iptv-nvidia-shield", kw: "iptv nvidia shield", kws: ["nvidia shield iptv setup", "shield tv iptv", "best iptv for nvidia shield"], anchor: "IPTV on Nvidia Shield",
    title: "IPTV on Nvidia Shield TV — Setup & Best Apps | MapleHD", desc: "IPTV on Nvidia Shield TV in Canada: why it's a top IPTV device, best apps (TiviMate, Smarters), 4K settings and how to add your MapleHD login.", h1: "IPTV on Nvidia Shield TV", badge: "IPTV · Nvidia Shield",
    answer: "The Nvidia Shield TV is one of the strongest devices for IPTV, with reliable 4K decoding, Ethernet and a long software-update record. Install TiviMate or IPTV Smarters Pro from Google Play, add your MapleHD Xtream Codes login and enable hardware decoding.",
    sections: [
      { h: "Why the Shield suits IPTV", ul: ["Strong hardware decoding for 4K", "Gigabit Ethernet for stable live sport", "Google TV/Android TV apps from Google Play", "Long-term software support compared with many boxes"] },
      { h: "Setup steps", ol: ["Complete first-time setup and connect Ethernet.", "Install TiviMate or IPTV Smarters Pro.", "Add your Xtream Codes login.", "Turn on hardware decoding and set a medium buffer."] },
      { h: "Price and alternatives", p: ["The Shield is a premium device. See the [best Android TV box for IPTV](/best-android-tv-box) and [Fire TV Stick 4K Max](/iptv-fire-tv-stick-4k-max) for lower-cost options."] },
    ],
    faq: [
      { q: "Is Nvidia Shield good for IPTV?", a: "Yes, it is widely considered one of the best devices for IPTV thanks to its decoding power and Ethernet." },
      { q: "Which app should I use on Shield?", a: "TiviMate or IPTV Smarters Pro." },
      { q: "Does Shield support 4K IPTV?", a: "Yes, with 4K sources and enough bandwidth." },
      { q: "Is there a cheaper alternative?", a: "The Fire TV Stick 4K Max is a good budget option." },
    ],
    related: ["iptv-google-tv", "best-android-tv-box", "iptv-android-tv-canada", "tivimate", "iptv-4k"],
  }),
  device({
    slug: "iptv-xbox", kw: "iptv xbox", kws: ["iptv on xbox", "xbox one iptv", "xbox series x iptv", "watch iptv on xbox"], anchor: "IPTV on Xbox",
    title: "IPTV on Xbox — What Works & Best Alternatives | MapleHD", desc: "Can you watch IPTV on an Xbox One or Series X|S? Learn the limits, browser and app options, and better ways to use MapleHD on your TV.", h1: "IPTV on Xbox: What Works and What Doesn't", badge: "IPTV · Xbox",
    answer: "Xbox consoles don't have a mainstream IPTV player app, so the simplest way to watch MapleHD is to use a Firestick, Android TV box or smart TV app on another HDMI input. Some browser-based playback may be possible but is less reliable for live sport.",
    sections: [
      { h: "Why Xbox is not a great IPTV device", p: ["Xbox focuses on games and major streaming apps. IPTV players are not generally listed, and browser playback depends on stream formats and site support."] },
      { h: "Better options", ul: ["[Fire TV Stick 4K](/iptv-fire-tv-stick-4k-max) for a low-cost dedicated device", "[Android TV box](/best-android-tv-box) for stronger 4K", "Your [smart TV](/iptv-smart-tv-canada) app", "[Chromecast](/iptv-chromecast) casting from a phone"] },
      { h: "Set up in short", ol: ["Add a streaming device to another HDMI input.", "Install a player and add your MapleHD login.", "Switch TV inputs between Xbox and the streaming device."], p2: ["See also [IPTV on PS5](/iptv-ps5)."] },
    ],
    faq: [
      { q: "Can I watch IPTV on an Xbox?", a: "Not with a mainstream IPTV app. Use a Firestick, Android TV box or smart TV app instead." },
      { q: "Does Xbox Series X support IPTV apps?", a: "Availability is limited. A dedicated streaming device is more reliable." },
      { q: "Can I use the Xbox browser for IPTV?", a: "Possibly, but it is unreliable for live sport." },
      { q: "What is the cheapest way to add IPTV to my TV?", a: "A Fire TV Stick is the lowest-cost option." },
    ],
    related: ["iptv-ps5", "iptv-devices", "iptv-firestick-canada", "best-android-tv-box", "iptv-chromecast"],
  }),
  device({
    slug: "iptv-generic-android-box", kw: "iptv generic android box", kws: ["cheap android tv box iptv", "no name android box iptv", "android box for iptv canada", "unbranded android tv box"], anchor: "generic Android box for IPTV",
    title: "Generic Android Box for IPTV — What to Check | MapleHD", desc: "Thinking of a cheap or unbranded Android box for IPTV? What specs matter, risks of no-name devices, how to set up and when to choose a brand instead.", h1: "Generic Android Boxes for IPTV: What to Check Before You Buy", badge: "Android Box · IPTV",
    answer: "A generic Android box can run IPTV apps like TiviMate and IPTV Smarters Pro, but quality varies widely. Check for 4K HEVC decoding, at least 2 GB of RAM, Ethernet, a current Android version and a return policy, and avoid boxes that claim free channels for life.",
    sections: [
      { h: "Spec checklist", table: { head: ["Spec", "Target"], rows: [["Video decoding", "4K HEVC hardware decoding"], ["RAM", "2 GB or more"], ["Storage", "16 GB or more"], ["Network", "Ethernet plus dual-band Wi-Fi"], ["Android version", "Recent, with app store access"]] } },
      { h: "Risks of no-name boxes", ul: ["Overstated specifications and fake RAM numbers", "Old Android versions with no updates", "Preinstalled apps you did not choose", "Poor warranty and support", "Claims of free channels that are not real"] },
      { h: "Set up a generic box", ol: ["Factory-reset the box and update it.", "Install TiviMate or IPTV Smarters Pro from a trusted source.", "Enter your MapleHD login.", "Enable hardware decoding and use Ethernet."], p2: ["For a safer choice, compare the [best Android TV boxes](/best-android-tv-box) and [Formuler](/formuler-iptv-box)."] },
    ],
    faq: [
      { q: "Is a cheap Android box good for IPTV?", a: "It can be if it has the right decoding and memory, but quality varies. Check specs and returns before buying." },
      { q: "Which apps work on a generic Android box?", a: "Most IPTV players run on Android: TiviMate, IPTV Smarters Pro, XCIPTV and OTT Navigator." },
      { q: "Do these boxes come with channels?", a: "No. You still need an IPTV subscription such as MapleHD." },
      { q: "Should I buy a branded box instead?", a: "For long-term reliability and updates, a branded device is usually safer." },
    ],
    related: ["best-android-tv-box", "iptv-box", "iptv-with-box", "iptv-boxes", "formuler-iptv-box"],
  }),
  device({
    slug: "iptv-tablets", kw: "iptv tablet", kws: ["iptv on ipad", "iptv android tablet", "best tablet for iptv", "watch iptv on tablet"], anchor: "IPTV on tablets",
    title: "IPTV on iPad & Android Tablets — Setup Guide | MapleHD", desc: "Watch IPTV on an iPad or Android tablet in Canada: best apps, casting to a TV, data use and battery tips for your MapleHD subscription.", h1: "IPTV on iPad and Android Tablets", badge: "IPTV · Tablets",
    answer: "Tablets are easy IPTV screens: install Smarters Player Lite or iPlayTV on an iPad, or IPTV Smarters Pro or XCIPTV on an Android tablet, then enter your MapleHD Xtream Codes login. Use Wi-Fi to save data, and cast to a TV when you want the big screen.",
    sections: [
      { h: "Best apps by tablet", ul: ["iPad: [Smarters Player Lite](/iptv-smarters-lite), [IMPlayer and iPlayTV](/implayer)", "Android tablets: [IPTV Smarters Pro](/iptv-smarters-pro-download), [XCIPTV](/xciptv), [OTT Navigator](/ott-navigator)"] },
      { h: "Setup steps", ol: ["Install the app from the official store.", "Choose Xtream Codes login.", "Enter your MapleHD details.", "Open live TV and add favourites."] },
      { h: "Data and battery tips", ul: ["Use Wi-Fi where possible: HD uses about 3 GB per hour.", "Lower stream quality on mobile data.", "Plug in during long sports events.", "Cast to a TV: see [Chromecast](/iptv-chromecast)."] },
    ],
    faq: [
      { q: "Can I watch IPTV on an iPad?", a: "Yes, with Smarters Player Lite, IMPlayer or iPlayTV." },
      { q: "What is the best IPTV app for Android tablets?", a: "IPTV Smarters Pro is the most popular; XCIPTV is another good option." },
      { q: "How much data does a tablet use?", a: "HD can use about 3 GB per hour or more. Use Wi-Fi." },
      { q: "Can I cast from a tablet to my TV?", a: "Many players support Chromecast casting." },
    ],
    related: ["iptv-ios-canada", "iptv-android-canada", "iptv-smarters-lite", "implayer", "iptv-devices"],
  }),

  // ---------------- French hockey ----------------
  {
    slug: "fr/iptv-canadiens", lang: "fr", cluster: "fr", kind: "guide", hub: "fr", pillar: "fr", hreflangPair: "iptv-canadiens",
    title: "IPTV Canadiens de Montréal — Regarder les matchs | MapleHD",
    desc: "Regardez les matchs des Canadiens avec l'IPTV au Canada : RDS, TVA Sports, HD et 4K, séries éliminatoires et essai gratuit. Forfaits dès 9 $/mois.",
    h1: "IPTV Canadiens de Montréal : comment regarder chaque match",
    badge: "IPTV Canadiens · LNH",
    kw: "iptv canadiens de montréal", kws: ["iptv canadiens", "habs iptv", "regarder canadiens iptv", "rds iptv", "tva sports iptv"],
    anchor: "IPTV Canadiens de Montréal",
    answer: "Pour regarder les Canadiens avec l'IPTV, choisissez un service qui inclut les chaînes sportives qui détiennent les droits, comme RDS et TVA Sports pour le français. MapleHD inclut des chaînes sportives canadiennes, diffuse en HD et en 4K et offre un essai gratuit pour tester un match en direct.",
    sections: [
      { h: "Où passent les matchs des Canadiens", p: ["Les matchs sont répartis entre des chaînes régionales et nationales, en français et en anglais. Les droits changent d'une saison à l'autre: confirmez toujours la chaîne dans le guide de votre lecteur.", "Pour les détails locaux, consultez [IPTV Montréal](/iptv-montreal), [IPTV Québec](/iptv-quebec) et [IPTV Laval](/iptv-laval)."] },
      { h: "Préparer un soir de match", ol: ["Testez la chaîne avant la mise au jeu.", "Utilisez Ethernet ou un Wi-Fi 5/6 solide.", "Activez le décodage matériel dans votre [lecteur IPTV](/fr/lecteur-iptv).", "Ajoutez la chaîne à vos favoris.", "Gardez un deuxième appareil prêt."] },
      { h: "Séries éliminatoires", p: ["Les soirs de séries, la demande explose. Un forfait avec plusieurs connexions permet de suivre un deuxième match sur une tablette. Voir l'[abonnement IPTV](/fr/abonnement-iptv)."] },
    ],
    faq: [
      { q: "Peut-on regarder les Canadiens en IPTV?", a: "Oui, par les chaînes sportives qui détiennent les droits. Testez la chaîne avec l'essai gratuit." },
      { q: "Quelle chaîne diffuse les Canadiens en français?", a: "Généralement RDS et TVA Sports, selon le match. Confirmez dans le guide." },
      { q: "Y a-t-il une version anglaise?", a: "Oui: [IPTV Canadiens (English)](/iptv-canadiens)." },
      { q: "Puis-je essayer avant de payer?", a: "Oui, un essai gratuit sans carte de crédit est offert. Voir la [page d'essai](/free-trial)." },
    ],
    related: ["fr", "iptv-quebec", "iptv-montreal", "iptv-canadiens", "iptv-nhl-canada"],
  },
];
