// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-vancouver-island");

export default function Pageiptv_vancouver_island() {
  return <SeoPage slug="iptv-vancouver-island" />;
}
