// Usage: node seo/coverage.mjs [-v] — reports which assigned keywords are NOT present in the visible text of their page.
// Uses seo/keyword-map.csv (run build-keyword-map.mjs first) and src/content/seo (new pages) + src/app/*/page.tsx (existing pages).
import { readFileSync, existsSync, writeFileSync } from "fs";
import { join } from "path";
import { PAGES } from "../src/content/seo/registry.mjs";

const root = new URL("../", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const norm = (s) => s.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").replace(/\s+/g, " ").trim();
const bySlug = new Map(PAGES.map((p) => [p.slug, p]));
const cache = new Map();
function textOf(slug) {
  if (cache.has(slug)) return cache.get(slug);
  let t = "";
  const p = bySlug.get(slug);
  if (p) {
    t = JSON.stringify({ t: p.title, d: p.desc, h: p.h1, b: p.badge, a: p.answer, s: p.sections, f: p.faq });
  } else {
    const f = join(root, "src/app", slug, "page.tsx");
    if (existsSync(f)) t = readFileSync(f, "utf8");
    // hand-written pages also carry FAQ/extras from existing.mjs
  }
  const n = " " + norm(t.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")) + " ";
  cache.set(slug, n);
  return n;
}

const rows = readFileSync(join(root, "seo/keyword-map.csv"), "utf8").split(/\r?\n/).slice(1).filter(Boolean).map((l) => {
  const m = l.match(/^"((?:[^"]|"")*)",(\d+),(\w+),\/([^,]*),/);
  return m && { kw: m[1].replace(/""/g, '"'), vol: +m[2], slug: m[4] };
}).filter(Boolean);

const gaps = [];
const per = new Map();
for (const r of rows) {
  const n = textOf(r.slug);
  const hit = n.includes(" " + norm(r.kw) + " ");
  const e = per.get(r.slug) || { total: 0, hit: 0 };
  e.total++;
  if (hit) e.hit++;
  per.set(r.slug, e);
  if (!hit) gaps.push(r);
}
writeFileSync(join(root, "seo/coverage-gaps.json"), JSON.stringify(gaps, null, 1));
// "Also searched as" data: uncovered variants per page (highest volume first, capped) rendered as a visible block.
const CAP = 30;
const also = {};
for (const g of [...gaps].sort((a, b) => b.vol - a.vol)) {
  (also[g.slug] = also[g.slug] || []).push(g.kw);
}
const capped = Object.fromEntries(Object.entries(also).map(([k, v]) => [k, v.slice(0, CAP)]));
writeFileSync(join(root, "src/content/seo/also-searched.mjs"), "// generated by seo/coverage.mjs — uncovered keyword variants per page\nexport default " + JSON.stringify(capped, null, 1) + ";\n");
const overflow = Object.entries(also).filter(([, v]) => v.length > CAP).map(([k, v]) => `${k}:${v.length - CAP}`);
if (overflow.length) console.log("over cap:", overflow.join(", "));
const pct = ((1 - gaps.length / rows.length) * 100).toFixed(1);
console.log(`keywords ${rows.length} | covered in visible text ${rows.length - gaps.length} (${pct}%) | gaps ${gaps.length} | gap volume ${gaps.reduce((s, g) => s + g.vol, 0)}`);
if (process.argv.includes("-v")) {
  const worst = [...per.entries()].map(([s, e]) => ({ s, ...e, miss: e.total - e.hit })).sort((a, b) => b.miss - a.miss).slice(0, 40);
  for (const w of worst) console.log(w.s.padEnd(34), `${w.hit}/${w.total}`);
}
