// Usage: node seo/generate-pages.mjs — writes src/app/<slug>/page.tsx for every page in src/content/seo.
// Refuses to overwrite hand-written pages (anything without the AUTO-GENERATED marker).
import { PAGES } from "../src/content/seo/registry.mjs";
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "app");
let written = 0;
for (const p of PAGES) {
  const file = join(root, ...p.slug.split("/"), "page.tsx");
  if (existsSync(file) && !readFileSync(file, "utf8").includes("AUTO-GENERATED")) {
    console.error(`SKIP (hand-written page exists): ${p.slug}`);
    continue;
  }
  mkdirSync(dirname(file), { recursive: true });
  const fn = "Page" + p.slug.replace(/[^a-z0-9]+/gi, "_");
  writeFileSync(
    file,
    `// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs\nimport SeoPage from "@/components/SeoPage";\nimport { seoMetadata } from "@/lib/seo";\n\nexport const metadata = seoMetadata(${JSON.stringify(p.slug)});\n\nexport default function ${fn}() {\n  return <SeoPage slug=${JSON.stringify(p.slug)} />;\n}\n`
  );
  written++;
}
console.log(`wrote ${written} page files`);
