// Usage: node seo/update-sitemap.mjs — adds every SEO page to public/sitemap.xml (idempotent), bumps lastmod on
// hand-written pages that received new internal links, and writes hreflang alternates for en/fr pairs.
import { readFileSync, writeFileSync } from "fs";
import { PAGES } from "../src/content/seo/registry.mjs";

const file = new URL("../public/sitemap.xml", import.meta.url);
const TODAY = "2026-09-27";
const BASE = "https://maplehd.ca";
let xml = readFileSync(file, "utf8");

if (!xml.includes("xmlns:xhtml")) {
  xml = xml.replace('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">');
}
// idempotent: drop a previously generated block
const marker = "\n  <!-- SEO cluster pages";
const at = xml.indexOf(marker);
if (at >= 0) xml = xml.slice(0, at) + "\n</urlset>\n";

const url = (slug) => (slug === "" ? BASE : `${BASE}/${slug}`);

// Replace text between two markers on the single line that contains `<loc>LOC</loc>`.
function editEntry(loc, fn) {
  const start = xml.indexOf(`<loc>${loc}</loc>`);
  if (start < 0) return;
  const lineStart = xml.lastIndexOf("\n", start) + 1;
  const lineEnd = xml.indexOf("\n", start);
  xml = xml.slice(0, lineStart) + fn(xml.slice(lineStart, lineEnd)) + xml.slice(lineEnd);
}

const touched = ["", "pricing", "free-trial", "blog", "about", "contact", "referral", "how-it-works", "channels-list", "reseller", "free-iptv-canada", "iptv-resellers", "iptv-installer", "iptv-reviews", "iptv-quebec", "iptv-smarters", "iptv-firestick-canada", "iptv-android-tv-canada", "iptv-android-canada", "iptv-apple-tv-canada", "iptv-ios-canada", "iptv-roku-canada", "iptv-samsung-tv-canada", "iptv-lg-tv-canada", "iptv-smart-tv-canada", "iptv-windows-canada", "iptv-mag-box-canada", "iptv-toronto", "iptv-vancouver", "iptv-montreal", "iptv-calgary", "iptv-ottawa", "iptv-edmonton", "iptv-winnipeg", "iptv-hamilton", "iptv-london-ontario", "blog/best-iptv-canada-2026", "blog/best-iptv-player-canada", "blog/is-iptv-legal-canada", "blog/iptv-vs-cable-canada", "blog/iptv-firestick-canada", "blog/iptv-samsung-tv-canada"];
for (const s of touched) {
  editEntry(url(s), (line) => {
    const a = line.indexOf("<lastmod>");
    const b = line.indexOf("</lastmod>");
    return a < 0 ? line : line.slice(0, a) + `<lastmod>${TODAY}` + line.slice(b);
  });
}

const alt = (en, fr) =>
  `<xhtml:link rel="alternate" hreflang="en-CA" href="${url(en)}"/><xhtml:link rel="alternate" hreflang="fr-CA" href="${url(fr)}"/><xhtml:link rel="alternate" hreflang="x-default" href="${url(en)}"/>`;
const pairs = PAGES.filter((p) => p.hreflangPair).map((p) => (p.lang === "fr" ? [p.hreflangPair, p.slug] : [p.slug, p.hreflangPair]));

const existingLocs = new Set([...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]));
// alternates on already-present (hand-written) counterparts
for (const [en, fr] of pairs) {
  editEntry(url(en), (line) => (line.includes("xhtml:link") ? line : line.replace(`<loc>${url(en)}</loc>`, `<loc>${url(en)}</loc>${alt(en, fr)}`)));
}

const prio = (p) => (p.kind === "hub" ? "0.85" : p.lang === "fr" ? "0.7" : p.kind === "landing" || p.kind === "compare" ? "0.9" : "0.75");
let block = "\n  <!-- SEO cluster pages (generated by seo/update-sitemap.mjs) -->\n";
let added = 0;
for (const p of PAGES) {
  if (existingLocs.has(url(p.slug))) continue;
  const pair = pairs.find(([en, fr]) => en === p.slug || fr === p.slug);
  block += `  <url><loc>${url(p.slug)}</loc>${pair ? alt(pair[0], pair[1]) : ""}<lastmod>${TODAY}</lastmod><changefreq>${p.kind === "hub" ? "weekly" : "monthly"}</changefreq><priority>${prio(p)}</priority></url>\n`;
  added++;
}
xml = xml.replace("</urlset>", block + "</urlset>");
writeFileSync(file, xml);
console.log(`sitemap: added ${added} URLs, total ${[...xml.matchAll(/<loc>/g)].length}`);
