// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-canadian-channels");

export default function Pageiptv_canadian_channels() {
  return <SeoPage slug="iptv-canadian-channels" />;
}
