// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-live-tv-24-7");

export default function Pageiptv_live_tv_24_7() {
  return <SeoPage slug="iptv-live-tv-24-7" />;
}
