// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-northwest-territories");

export default function Pageiptv_northwest_territories() {
  return <SeoPage slug="iptv-northwest-territories" />;
}
