// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-plex-emby-jellyfin");

export default function Pageiptv_plex_emby_jellyfin() {
  return <SeoPage slug="iptv-plex-emby-jellyfin" />;
}
