// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-charlottetown");

export default function Pageiptv_charlottetown() {
  return <SeoPage slug="iptv-charlottetown" />;
}
