// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-espn-sky-sports");

export default function Pageiptv_espn_sky_sports() {
  return <SeoPage slug="iptv-espn-sky-sports" />;
}
