// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/liste-m3u-iptv");

export default function Pagefr_liste_m3u_iptv() {
  return <SeoPage slug="fr/liste-m3u-iptv" />;
}
