// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("kemo-iptv");

export default function Pagekemo_iptv() {
  return <SeoPage slug="kemo-iptv" />;
}
