// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-vs-cable-hub");

export default function Pageiptv_vs_cable_hub() {
  return <SeoPage slug="iptv-vs-cable-hub" />;
}
