// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-dvr-catch-up");

export default function Pageiptv_dvr_catch_up() {
  return <SeoPage slug="iptv-dvr-catch-up" />;
}
