// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-mount-pearl");

export default function Pageiptv_mount_pearl() {
  return <SeoPage slug="iptv-mount-pearl" />;
}
