// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-tsn");

export default function Pageiptv_tsn() {
  return <SeoPage slug="iptv-tsn" />;
}
