// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-near-me");

export default function Pageiptv_near_me() {
  return <SeoPage slug="iptv-near-me" />;
}
