// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("king365-tv");

export default function Pageking365_tv() {
  return <SeoPage slug="king365-tv" />;
}
