// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("android-tv-box-models");

export default function Pageandroid_tv_box_models() {
  return <SeoPage slug="android-tv-box-models" />;
}
