// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-mississauga");

export default function Pageiptv_mississauga() {
  return <SeoPage slug="iptv-mississauga" />;
}
