// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-with-box");

export default function Pageiptv_with_box() {
  return <SeoPage slug="iptv-with-box" />;
}
