// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/meilleur-iptv-canada");

export default function Pagefr_meilleur_iptv_canada() {
  return <SeoPage slug="fr/meilleur-iptv-canada" />;
}
