// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("tvip-iptv-box");

export default function Pagetvip_iptv_box() {
  return <SeoPage slug="tvip-iptv-box" />;
}
