// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-prince-edward-island");

export default function Pageiptv_prince_edward_island() {
  return <SeoPage slug="iptv-prince-edward-island" />;
}
