// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("buzztv-iptv");

export default function Pagebuzztv_iptv() {
  return <SeoPage slug="buzztv-iptv" />;
}
