// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-red-deer");

export default function Pageiptv_red_deer() {
  return <SeoPage slug="iptv-red-deer" />;
}
