// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-newfoundland-and-labrador");

export default function Pageiptv_newfoundland_and_labrador() {
  return <SeoPage slug="iptv-newfoundland-and-labrador" />;
}
