// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-nova-scotia");

export default function Pageiptv_nova_scotia() {
  return <SeoPage slug="iptv-nova-scotia" />;
}
