// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-service-canada");

export default function Pageiptv_service_canada() {
  return <SeoPage slug="iptv-service-canada" />;
}
