// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("formuler-z11");

export default function Pageformuler_z11() {
  return <SeoPage slug="formuler-z11" />;
}
