// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-fire-tv-stick-4k-max");

export default function Pageiptv_fire_tv_stick_4k_max() {
  return <SeoPage slug="iptv-fire-tv-stick-4k-max" />;
}
