// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-4k");

export default function Pageiptv_4k() {
  return <SeoPage slug="iptv-4k" />;
}
