// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/iptv-legal");

export default function Pagefr_iptv_legal() {
  return <SeoPage slug="fr/iptv-legal" />;
}
