// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-brandon");

export default function Pageiptv_brandon() {
  return <SeoPage slug="iptv-brandon" />;
}
