// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/iptv-sur-smart-tv");

export default function Pagefr_iptv_sur_smart_tv() {
  return <SeoPage slug="fr/iptv-sur-smart-tv" />;
}
