// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-oilers");

export default function Pageiptv_oilers() {
  return <SeoPage slug="iptv-oilers" />;
}
