// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-smarters-pro-pc-mac");

export default function Pageiptv_smarters_pro_pc_mac() {
  return <SeoPage slug="iptv-smarters-pro-pc-mac" />;
}
