// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-manitoba");

export default function Pageiptv_manitoba() {
  return <SeoPage slug="iptv-manitoba" />;
}
