// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("cheap-iptv-canada");

export default function Pagecheap_iptv_canada() {
  return <SeoPage slug="cheap-iptv-canada" />;
}
