// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-enigma2");

export default function Pageiptv_enigma2() {
  return <SeoPage slug="iptv-enigma2" />;
}
