// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("forever-tv");

export default function Pageforever_tv() {
  return <SeoPage slug="forever-tv" />;
}
