// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-cbc");

export default function Pageiptv_cbc() {
  return <SeoPage slug="iptv-cbc" />;
}
