// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/abonnement-iptv");

export default function Pagefr_abonnement_iptv() {
  return <SeoPage slug="fr/abonnement-iptv" />;
}
