// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-maple-leafs");

export default function Pageiptv_maple_leafs() {
  return <SeoPage slug="iptv-maple-leafs" />;
}
