// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-m3u-player");

export default function Pageiptv_m3u_player() {
  return <SeoPage slug="iptv-m3u-player" />;
}
