// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-royal-premium-brand-names");

export default function Pageiptv_royal_premium_brand_names() {
  return <SeoPage slug="iptv-royal-premium-brand-names" />;
}
