// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-saint-john");

export default function Pageiptv_saint_john() {
  return <SeoPage slug="iptv-saint-john" />;
}
