// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("buy-iptv");

export default function Pagebuy_iptv() {
  return <SeoPage slug="buy-iptv" />;
}
