// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("smart-iptv-app");

export default function Pagesmart_iptv_app() {
  return <SeoPage slug="smart-iptv-app" />;
}
