// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-british-columbia");

export default function Pageiptv_british_columbia() {
  return <SeoPage slug="iptv-british-columbia" />;
}
