// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-tcl-tv");

export default function Pageiptv_tcl_tv() {
  return <SeoPage slug="iptv-tcl-tv" />;
}
