// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-dartmouth");

export default function Pageiptv_dartmouth() {
  return <SeoPage slug="iptv-dartmouth" />;
}
