// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/iptv-smarters-pro");

export default function Pagefr_iptv_smarters_pro() {
  return <SeoPage slug="fr/iptv-smarters-pro" />;
}
