// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-vs-rogers");

export default function Pageiptv_vs_rogers() {
  return <SeoPage slug="iptv-vs-rogers" />;
}
