// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-prince-albert");

export default function Pageiptv_prince_albert() {
  return <SeoPage slug="iptv-prince-albert" />;
}
