// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("tivimate-smart-tv");

export default function Pagetivimate_smart_tv() {
  return <SeoPage slug="tivimate-smart-tv" />;
}
