// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("apollo-iptv");

export default function Pageapollo_iptv() {
  return <SeoPage slug="apollo-iptv" />;
}
