// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-providers-canada");

export default function Pageiptv_providers_canada() {
  return <SeoPage slug="iptv-providers-canada" />;
}
