// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("premium-iptv");

export default function Pagepremium_iptv() {
  return <SeoPage slug="premium-iptv" />;
}
