// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-canadian-holidays");

export default function Pageiptv_canadian_holidays() {
  return <SeoPage slug="iptv-canadian-holidays" />;
}
