// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("tivimate-pc-mac");

export default function Pagetivimate_pc_mac() {
  return <SeoPage slug="tivimate-pc-mac" />;
}
