// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("fr/lecteur-iptv");

export default function Pagefr_lecteur_iptv() {
  return <SeoPage slug="fr/lecteur-iptv" />;
}
