// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("best-iptv-reddit");

export default function Pagebest_iptv_reddit() {
  return <SeoPage slug="best-iptv-reddit" />;
}
