// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-smarters-apple");

export default function Pageiptv_smarters_apple() {
  return <SeoPage slug="iptv-smarters-apple" />;
}
