// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("xtream-iptv-player");

export default function Pagextream_iptv_player() {
  return <SeoPage slug="xtream-iptv-player" />;
}
