// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-lower-mainland");

export default function Pageiptv_lower_mainland() {
  return <SeoPage slug="iptv-lower-mainland" />;
}
