// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-time-zones-canada");

export default function Pageiptv_time_zones_canada() {
  return <SeoPage slug="iptv-time-zones-canada" />;
}
