// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-moose-jaw");

export default function Pageiptv_moose_jaw() {
  return <SeoPage slug="iptv-moose-jaw" />;
}
