// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("best-android-tv-box");

export default function Pagebest_android_tv_box() {
  return <SeoPage slug="best-android-tv-box" />;
}
