// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("formuler-iptv-box");

export default function Pageformuler_iptv_box() {
  return <SeoPage slug="formuler-iptv-box" />;
}
