// AUTO-GENERATED by seo/generate-pages.mjs — edit content in src/content/seo/*.mjs
import SeoPage from "@/components/SeoPage";
import { seoMetadata } from "@/lib/seo";

export const metadata = seoMetadata("iptv-extreme");

export default function Pageiptv_extreme() {
  return <SeoPage slug="iptv-extreme" />;
}
